## Numpy is the core library for scientific computing in Python.

#### It provides a high-performance multidimensional array object, and tools for working with these arrays.
##### If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

## Why not List?

In [1]:
p= [5,8,1,3]

In [3]:
p+2
# output: [7, 10, 2, 5]

In [5]:
p*2
# output: [14, 20, 4, 10]
# its showing same value two times

[5, 8, 1, 3, 5, 8, 1, 3]

In [6]:
# self addition
p+p

[5, 8, 1, 3, 5, 8, 1, 3]

In [17]:
# p-5

In [8]:
# p*p

# These are the reasons, developers swithced to Numpy....

In computer programming, an array is a structure for storing and retrieving data. We often talk about an array as if it were a grid in space, with each cell storing one element of the data. For instance, if each element of the data were a number, we might visualize a “one-dimensional” array like a list:

Having same kind of values in array

In [9]:
# import NumPy library
import numpy as np


In [11]:
a = np.array([2,5,8])  # Create a rank of 1 array
print(type(a))         # Prints "<class 'numpy.ndarray'>"
print(a.shape)         # Prints "(3,)"

<class 'numpy.ndarray'>
(3,)


In [12]:
b = np.array([[2,5,8],[1,9,3]])
print(b.shape)

(2, 3)


In [13]:
a

array([2, 5, 8])

In [14]:
# addition
a+2

array([ 4,  7, 10])

In [15]:
# multiplication
a*2

array([ 4, 10, 16])

In [19]:
# Substraction
print(a)
print(a-5)

[2 5 8]
[-3  0  3]


In [21]:
# self addition
print(a)
print(a+a)

[2 5 8]
[ 4 10 16]


In [24]:
# self production
print(a)
print('*************************')
print(a*a)

[2 5 8]
*************************
[ 4 25 64]


In [26]:
# Create an array of all zeros
c= np.zeros((5,6))
print(c)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [28]:
# Create an array of all ones
c= np.ones((3,4))    # 3 rows and 4 columns
print(c)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [32]:
# Create a constant array
c= np.full((5,3),8)    # 3 rows and 4 columns
print(c)

[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


# Random values

In [40]:
e = np.random.random((2,3)) # Create an array filled with random values
print(e)

[[0.92744014 0.8759802  0.40226412]
 [0.25336497 0.96379702 0.01892262]]


In [41]:
# lets create three dimension array
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [47]:
# lets create three dimension array
b = np.array([[10,20,31,41], [15,16,72,82], [92,102,121,122]])

In [42]:
# method 1
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
# method 2
print(a.shape)

(3, 4)


In [46]:
bool_index = (a>5)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.
print(bool_index)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [48]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
b

array([[ 10,  20,  31,  41],
       [ 15,  16,  72,  82],
       [ 92, 102, 121, 122]])

In [52]:
print("Matrix A\n", a)
print('*************************')
print('*************************')
print("Matrix B\n", b)

Matrix A
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
*************************
*************************
Matrix B
 [[ 10  20  31  41]
 [ 15  16  72  82]
 [ 92 102 121 122]]


In [53]:
print('Regular matrix addition A+B\n',a+b)

Regular matrix addition A+B
 [[ 11  22  34  45]
 [ 20  22  79  90]
 [101 112 132 134]]


In [55]:
print("Matrix A\n", a)
print('*************************')
print('*************************')
print("Addition using Broadcasting A+5\n", a + 5)

Matrix A
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
*************************
*************************
Addition using Broadcasting A+5
 [[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


In [66]:
a = np.array([[1,2], [3, 4], [5, 6]])
print("Matrix A\n", a)
print('*************************')
print("Transposed Matrix\n",a.T)

Matrix A
 [[1 2]
 [3 4]
 [5 6]]
*************************
Transposed Matrix
 [[1 3 5]
 [2 4 6]]
